/**
 * Tests for the design-token generator (issue #849). Run with:
 *   node --test scripts/design-tokens/
 *
 * Stdlib node:test only — no npm dependencies, matching the generator itself.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  loadTokens,
  resolveColor,
  buildOutputs,
  run,
  emitIosColors,
  emitAndroidColors,
  emitSkillDoc,
  THEMES,
  emitGoTokens,
  emitSharepageTokensGohtml,
} from './generate.mjs';

const HERE = dirname(fileURLToPath(new URL(import.meta.url)));
const GENERATE = join(HERE, 'generate.mjs');
const REPO_ROOT = join(HERE, '..', '..');
const tokens = loadTokens();

const IOS_COLORS_PATH = join(
  REPO_ROOT,
  'mobile', 'ios', 'packages', 'town-crier-presentation',
  'Sources', 'DesignSystem', 'Colors', 'Color+TownCrier.swift',
);
const ANDROID_COLORS_PATH = join(
  REPO_ROOT,
  'mobile', 'android', 'presentation', 'src', 'main', 'kotlin',
  'uk', 'towncrierapp', 'presentation', 'designsystem', 'Color.kt',
);
const SKILL_DOC_PATH = join(REPO_ROOT, '.claude', 'skills', 'design-language', 'references', 'tokens.md');
const SKILL_BEGIN = '<!-- tokens:generated:begin -->';
const SKILL_END = '<!-- tokens:generated:end -->';

test('resolveColor returns the direct per-theme value', () => {
  assert.equal(resolveColor(tokens.color, 'amber', 'light'), '#9E6709');
  assert.equal(resolveColor(tokens.color, 'amber', 'dark'), '#E9A620');
  assert.equal(resolveColor(tokens.color, 'amber', 'oled'), '#E9A620');
  assert.equal(resolveColor(tokens.color, 'background', 'oled'), '#000000');
});

test('resolveColor follows a base reference with no alpha (per theme)', () => {
  // border-focused: { base: "amber" } -> amber's hex, resolved per theme.
  assert.equal(
    resolveColor(tokens.color, 'border-focused', 'light'),
    resolveColor(tokens.color, 'amber', 'light'),
  );
  assert.equal(resolveColor(tokens.color, 'border-focused', 'dark'), '#E9A620');
});

test('resolveColor emits rgba() for a per-theme alpha over a token base', () => {
  // amber-muted: { base: "amber", alpha: { light: 0.12, dark: 0.15, oled: 0.15 } }
  // -> rgba of amber at the per-theme alpha.
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'light'), 'rgba(158, 103, 9, 0.12)');
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'dark'), 'rgba(233, 166, 32, 0.15)');
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'oled'), 'rgba(233, 166, 32, 0.15)');
});

test('resolveColor emits rgba() for a per-theme alpha over a literal base', () => {
  // overlay: { base: "#000000", alpha: { light: 0.4, dark: 0.5, oled: 0.5 } }
  assert.equal(resolveColor(tokens.color, 'overlay', 'light'), 'rgba(0, 0, 0, 0.4)');
  assert.equal(resolveColor(tokens.color, 'overlay', 'dark'), 'rgba(0, 0, 0, 0.5)');
  assert.equal(resolveColor(tokens.color, 'overlay', 'oled'), 'rgba(0, 0, 0, 0.5)');
});

test('resolveColor throws on an unknown token', () => {
  assert.throws(() => resolveColor(tokens.color, 'no-such-token', 'light'), /unknown colour token/);
});

test('every colour token resolves for all three themes (light/dark/oled)', () => {
  for (const name of Object.keys(tokens.color)) {
    for (const theme of THEMES) {
      const value = resolveColor(tokens.color, name, theme);
      assert.ok(
        typeof value === 'string' && value.length > 0,
        `colour token "${name}" produced no value for theme "${theme}"`,
      );
    }
  }
});

test('direct (non-ref) colour tokens declare all three themes explicitly', () => {
  for (const [name, entry] of Object.entries(tokens.color)) {
    if ('base' in entry) continue; // refs inherit their themes from the base
    for (const theme of THEMES) {
      assert.ok(theme in entry, `colour token "${name}" is missing the "${theme}" theme`);
    }
  }
});

test('generation is idempotent — buildOutputs is a pure function of tokens.json', () => {
  const a = buildOutputs(tokens);
  const b = buildOutputs(loadTokens());
  assert.deepEqual(
    a.map((o) => o.content),
    b.map((o) => o.content),
  );
});

// --------------------------------------------------------------------------
// Go emitter: api-go/internal/designtokens/tokens_gen.go
// --------------------------------------------------------------------------

test('emitGoTokens emits the generated-code marker, package clause, and import', () => {
  const go = emitGoTokens(tokens);
  assert.match(go, /^\/\/ Code generated by scripts\/design-tokens\/generate\.mjs\. DO NOT EDIT\./);
  assert.match(go, /\npackage designtokens\n/);
  assert.match(go, /import "image\/color"/);
});

test('emitGoTokens emits hex-string consts per theme, light+dark only (no OLED)', () => {
  const go = emitGoTokens(tokens);
  assert.match(go, /AmberLightHex\s+= "#9E6709"/);
  assert.match(go, /AmberDarkHex\s+= "#E9A620"/);
  // A base-ref token (border-focused -> amber) still resolves to a concrete hex.
  assert.match(go, /BorderFocusedLightHex\s+= "#9E6709"/);
  // Symbols are PascalCase (…OledHex); the doc's all-caps "OLED" must not match,
  // so this stays case-sensitive.
  assert.ok(!/Oled/.test(go), 'no Go-rendered surface implements OLED — no Oled symbol should be emitted');
});

test('emitGoTokens converts hex to color.RGBA correctly (incl. zero-padded low byte)', () => {
  const go = emitGoTokens(tokens);
  // #9E6709 -> R:0x9E G:0x67 B:0x09 — the 0x09 verifies two-digit padding.
  assert.match(go, /AmberLight\s+= color\.RGBA\{R: 0x9E, G: 0x67, B: 0x09, A: 0xFF\}/);
  assert.match(go, /AmberDark\s+= color\.RGBA\{R: 0xE9, G: 0xA6, B: 0x20, A: 0xFF\}/);
  // White is an emitted image-renderer primitive, not a token.
  assert.match(go, /var White = color\.RGBA\{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF\}/);
});

test('emitGoTokens omits the alpha tokens (amber-muted, overlay) that are not solid hex', () => {
  const go = emitGoTokens(tokens);
  assert.ok(!/AmberMuted/.test(go), 'amber-muted resolves to rgba(), not a solid hex');
  assert.ok(!/Overlay/.test(go), 'overlay resolves to rgba(), not a solid hex');
});

test('emitGoTokens aligns each const/var block so every = shares one column (gofmt-clean)', () => {
  const go = emitGoTokens(tokens);
  const blocks = go.match(/(?:const|var) \(\n([\s\S]*?)\n\)/g) ?? [];
  assert.ok(blocks.length === 2, 'expected exactly a const block and a var block');
  for (const block of blocks) {
    const cols = block
      .split('\n')
      .filter((l) => l.includes(' = '))
      .map((l) => l.indexOf(' = '));
    assert.ok(cols.length > 0);
    assert.ok(cols.every((c) => c === cols[0]), 'assignment "=" not aligned within a block');
  }
});

// --------------------------------------------------------------------------
// Share-page emitter: api-go/internal/sharepage/templates/tokens.gohtml
// --------------------------------------------------------------------------

test('emitSharepageTokensGohtml wraps a tokenVars block with light :root and dark @media', () => {
  const html = emitSharepageTokensGohtml(tokens);
  assert.match(html, /\{\{define "tokenVars"\}\}/);
  assert.match(html, /\{\{end\}\}/);
  assert.match(html, /:root\{/);
  assert.match(html, /@media \(prefers-color-scheme:dark\)\{/);
  // Provenance is a Go-template comment so it renders zero bytes into the CSS.
  assert.match(html, /\{\{\/\* GENERATED FILE/);
});

test('emitSharepageTokensGohtml uses the true neutral bucket (withdrawn), unlike the SEO block', () => {
  const html = emitSharepageTokensGohtml(tokens);
  // statusBuckets.neutral = status-withdrawn: #7A7570 light, #8E8A85 dark.
  assert.match(html, /--status-neutral:#7A7570;/);
  assert.match(html, /--status-neutral:#8E8A85;/);
  // Not text-secondary (#6B6560 / #9B9590) — that is the SEO block's neutral.
  assert.ok(!/--status-neutral:#6B6560/.test(html));
});

test('emitSharepageTokensGohtml emits compact rgba() fills at 15% (share-page style)', () => {
  const html = emitSharepageTokensGohtml(tokens);
  assert.match(html, /--status-granted-bg:rgba\(26,125,55,0\.15\);/); // #1A7D37 @ 15%
  assert.match(html, /--amber-muted:rgba\(158,103,9,0\.12\);/); // amber light @ 12%
  assert.ok(!/rgba\(26, 125, 55/.test(html), 'share-page rgba() has no spaces after commas');
});

test('emitSharepageTokensGohtml keeps layout invariants (radius/spacing) on the light :root only', () => {
  const html = emitSharepageTokensGohtml(tokens);
  const dark = html.slice(html.indexOf('@media'));
  assert.ok(!/--radius-sm/.test(dark), 'radius lives only on the light :root');
  assert.ok(!/--space-xs/.test(dark), 'spacing lives only on the light :root');
});

// --------------------------------------------------------------------------
// Drift gate: every generated output, tampered, fails --check
// --------------------------------------------------------------------------

test('--check exits 0 on a clean tree and non-zero once ANY generated file is tampered', () => {
  // Clean tree first (the committed files must already be in sync).
  execFileSync('node', [GENERATE, '--check'], { stdio: 'pipe' });

  // web(2) + Go(2) + iOS + Android + skill doc = every generated surface.
  assert.equal(buildOutputs(tokens).length, 7, 'expected web(2) + Go(2) + iOS + Android + skill doc');

  for (const { path } of buildOutputs(tokens)) {
    const original = readFileSync(path, 'utf8');
    // Tamper so the file no longer matches what the generator would produce.
    // The skill doc regenerates only between its markers, so tamper inside them;
    // every other output regenerates wholly, so a trailing language-appropriate
    // comment is enough (and keeps the file syntactically valid).
    const tampered = original.includes(SKILL_BEGIN)
      ? original.replace(SKILL_BEGIN, `${SKILL_BEGIN}\n<!-- tampered -->`)
      : original +
        (path.endsWith('.go')
          ? '\n// tampered\n'
          : path.endsWith('.gohtml')
            ? '\n{{/* tampered */}}\n'
            : '\n/* tampered */\n');
    try {
      writeFileSync(path, tampered);
      let exitCode = 0;
      try {
        execFileSync('node', [GENERATE, '--check'], { stdio: 'pipe' });
      } catch (err) {
        exitCode = err.status;
      }
      assert.notEqual(exitCode, 0, `--check should fail when ${path} is stale`);
    } finally {
      // Restore the committed content regardless of assertion outcome.
      run(); // regenerate from tokens.json
      assert.equal(readFileSync(path, 'utf8'), original, `generated file ${path} was not restored`);
    }
  }
});

// --------------------------------------------------------------------------
// Mobile colour emitters (T3, issue #851)
// --------------------------------------------------------------------------

test('emitIosColors reproduces the committed Color+TownCrier.swift byte-for-byte', () => {
  assert.equal(emitIosColors(tokens), readFileSync(IOS_COLORS_PATH, 'utf8'));
});

test('emitIosColors leads with the generated-file header', () => {
  const out = emitIosColors(tokens);
  assert.ok(out.startsWith('// Code generated by scripts/design-tokens/generate.mjs. DO NOT EDIT.\n\nimport SwiftUI\n'));
});

test('emitIosColors skips amber-hover (per-platform skip list)', () => {
  const out = emitIosColors(tokens);
  assert.ok(!out.includes('tcAmberHover'), 'iOS must not gain an amber-hover token');
  assert.ok(!out.includes('amber-hover'));
  assert.ok(out.includes('public static let tcAmber ='));
});

test('emitIosColors renders derived tokens in their iOS forms', () => {
  const out = emitIosColors(tokens);
  assert.ok(out.includes('public static let tcAmberMuted = tcAmber.opacity(0.12)'));
  assert.ok(out.includes('public static let tcBorderFocused = tcAmber\n'));
  // overlay is a flat scrim using the light-theme alpha, not a themed colour.
  assert.ok(out.includes('public static let tcOverlay = Color.black.opacity(0.4)'));
});

test('emitIosColors wraps status-rejected but keeps status-appealed inline (byte-exact wrapping)', () => {
  const out = emitIosColors(tokens);
  assert.ok(out.includes('public static let tcStatusRejected = Color.themed(\n    light: 0xC42B2B, dark: 0xFF453A, oled: 0xFF453A)'));
  assert.ok(out.includes('public static let tcStatusAppealed = Color.themed(light: 0x7C3AED, dark: 0xA78BFA, oled: 0xA78BFA)'));
});

test('emitAndroidColors reproduces the committed Color.kt byte-for-byte', () => {
  assert.equal(emitAndroidColors(tokens), readFileSync(ANDROID_COLORS_PATH, 'utf8'));
});

test('emitAndroidColors keeps amber-hover and formats overlay alpha per theme', () => {
  const out = emitAndroidColors(tokens);
  assert.ok(out.includes('amberHover = Color(0xFF8A5F06)'));
  assert.ok(out.includes('overlay = Color.Black.copy(alpha = 0.40f)'), 'light overlay alpha');
  assert.ok(out.includes('overlay = Color.Black.copy(alpha = 0.50f)'), 'dark overlay alpha');
  assert.ok(
    out.includes('amberMuted = Color(0xFF9E6709).copy(alpha = 0.12f)'),
    'amber-muted is amber at the per-theme light alpha (0.12)',
  );
});

test('emitAndroidColors OledPalette overrides exactly the four differing fields', () => {
  const out = emitAndroidColors(tokens);
  const oledBlock = out.slice(out.indexOf('DarkPalette.copy('));
  const overridden = [...oledBlock.matchAll(/^ {8}(\w+) =/gm)].map((m) => m[1]);
  assert.deepEqual(overridden, ['background', 'surface', 'surfaceElevated', 'border']);
});

// --------------------------------------------------------------------------
// Skill-doc emitter (T3, issue #851)
// --------------------------------------------------------------------------

test('emitSkillDoc reproduces the committed tokens.md byte-for-byte', () => {
  assert.equal(emitSkillDoc(tokens), readFileSync(SKILL_DOC_PATH, 'utf8'));
});

test('emitSkillDoc regenerates only between the markers; outside prose survives', () => {
  const original = readFileSync(SKILL_DOC_PATH, 'utf8');
  try {
    // Add a prose line after the end marker and tamper inside the markers.
    const withProse = original.replace(SKILL_END, `${SKILL_END}\n\nHAND-WRITTEN SENTINEL`);
    const tampered = withProse.replace(SKILL_BEGIN, `${SKILL_BEGIN}\n<!-- junk -->`);
    writeFileSync(SKILL_DOC_PATH, tampered);

    const regenerated = emitSkillDoc(tokens);
    assert.ok(regenerated.includes('HAND-WRITTEN SENTINEL'), 'prose outside the markers must survive');
    assert.ok(!regenerated.includes('<!-- junk -->'), 'content between the markers is regenerated');
    assert.ok(regenerated.includes('`TcPalette.statusConditions`'), 'tables are present');
  } finally {
    writeFileSync(SKILL_DOC_PATH, original);
  }
});

test('emitSkillDoc uses real names, includes status-conditions, drops the drifted names', () => {
  const out = emitSkillDoc(tokens);
  const generated = out.slice(out.indexOf(SKILL_BEGIN), out.indexOf(SKILL_END));
  assert.ok(!out.includes('tcStatusApproved'), 'the drifted tcStatusApproved name is gone');
  assert.ok(!out.includes('tcStatusRefused'), 'the drifted tcStatusRefused name is gone');
  assert.ok(!out.includes('tcSpaceMD'), 'the drifted tcSpaceMD name is gone');
  assert.ok(generated.includes('`status-conditions`'), 'status-conditions is documented');
  assert.ok(generated.includes('`Color.tcStatusPermitted`') && generated.includes('`TCSpacing.medium`'));
  // web-only / web+android tokens are qualified by the platforms column.
  assert.ok(/`amber-hover` \|.*\| — \|.*\| Web, Android \|/.test(generated), 'amber-hover marked web+Android, no iOS');
  assert.ok(/`card` \|.*\| Web \|/.test(generated), 'shadows marked web-only');
});
