/**
 * Tests for the design-token generator (issue #849). Run with:
 *   node --test scripts/design-tokens/
 *
 * Stdlib node:test only — no npm dependencies, matching the generator itself.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  loadTokens,
  resolveColor,
  buildOutputs,
  run,
  THEMES,
  emitGoTokens,
  emitSharepageTokensGohtml,
} from './generate.mjs';

const HERE = dirname(fileURLToPath(new URL(import.meta.url)));
const GENERATE = join(HERE, 'generate.mjs');
const REPO_ROOT = join(HERE, '..', '..');
const tokens = loadTokens();

test('resolveColor returns the direct per-theme value', () => {
  assert.equal(resolveColor(tokens.color, 'amber', 'light'), '#D4910A');
  assert.equal(resolveColor(tokens.color, 'amber', 'dark'), '#E9A620');
  assert.equal(resolveColor(tokens.color, 'amber', 'oled'), '#E9A620');
  assert.equal(resolveColor(tokens.color, 'background', 'oled'), '#000000');
});

test('resolveColor follows a base reference with no alpha (per theme)', () => {
  // border-focused: { base: "amber" } -> amber's hex, resolved per theme.
  assert.equal(
    resolveColor(tokens.color, 'border-focused', 'light'),
    resolveColor(tokens.color, 'amber', 'light'),
  );
  assert.equal(resolveColor(tokens.color, 'border-focused', 'dark'), '#E9A620');
});

test('resolveColor emits rgba() for a scalar alpha over a token base', () => {
  // amber-muted: { base: "amber", alpha: 0.15 } -> rgba of amber, 15%.
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'light'), 'rgba(212, 145, 10, 0.15)');
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'dark'), 'rgba(233, 166, 32, 0.15)');
  assert.equal(resolveColor(tokens.color, 'amber-muted', 'oled'), 'rgba(233, 166, 32, 0.15)');
});

test('resolveColor emits rgba() for a per-theme alpha over a literal base', () => {
  // overlay: { base: "#000000", alpha: { light: 0.4, dark: 0.5, oled: 0.5 } }
  assert.equal(resolveColor(tokens.color, 'overlay', 'light'), 'rgba(0, 0, 0, 0.4)');
  assert.equal(resolveColor(tokens.color, 'overlay', 'dark'), 'rgba(0, 0, 0, 0.5)');
  assert.equal(resolveColor(tokens.color, 'overlay', 'oled'), 'rgba(0, 0, 0, 0.5)');
});

test('resolveColor throws on an unknown token', () => {
  assert.throws(() => resolveColor(tokens.color, 'no-such-token', 'light'), /unknown colour token/);
});

test('every colour token resolves for all three themes (light/dark/oled)', () => {
  for (const name of Object.keys(tokens.color)) {
    for (const theme of THEMES) {
      const value = resolveColor(tokens.color, name, theme);
      assert.ok(
        typeof value === 'string' && value.length > 0,
        `colour token "${name}" produced no value for theme "${theme}"`,
      );
    }
  }
});

test('direct (non-ref) colour tokens declare all three themes explicitly', () => {
  for (const [name, entry] of Object.entries(tokens.color)) {
    if ('base' in entry) continue; // refs inherit their themes from the base
    for (const theme of THEMES) {
      assert.ok(theme in entry, `colour token "${name}" is missing the "${theme}" theme`);
    }
  }
});

test('generation is idempotent — buildOutputs is a pure function of tokens.json', () => {
  const a = buildOutputs(tokens);
  const b = buildOutputs(loadTokens());
  assert.deepEqual(
    a.map((o) => o.content),
    b.map((o) => o.content),
  );
});

// --------------------------------------------------------------------------
// Go emitter: api-go/internal/designtokens/tokens_gen.go
// --------------------------------------------------------------------------

test('emitGoTokens emits the generated-code marker, package clause, and import', () => {
  const go = emitGoTokens(tokens);
  assert.match(go, /^\/\/ Code generated by scripts\/design-tokens\/generate\.mjs\. DO NOT EDIT\./);
  assert.match(go, /\npackage designtokens\n/);
  assert.match(go, /import "image\/color"/);
});

test('emitGoTokens emits hex-string consts per theme, light+dark only (no OLED)', () => {
  const go = emitGoTokens(tokens);
  assert.match(go, /AmberLightHex\s+= "#D4910A"/);
  assert.match(go, /AmberDarkHex\s+= "#E9A620"/);
  // A base-ref token (border-focused -> amber) still resolves to a concrete hex.
  assert.match(go, /BorderFocusedLightHex\s+= "#D4910A"/);
  // Symbols are PascalCase (…OledHex); the doc's all-caps "OLED" must not match,
  // so this stays case-sensitive.
  assert.ok(!/Oled/.test(go), 'no Go-rendered surface implements OLED — no Oled symbol should be emitted');
});

test('emitGoTokens converts hex to color.RGBA correctly (incl. zero-padded low byte)', () => {
  const go = emitGoTokens(tokens);
  // #D4910A -> R:0xD4 G:0x91 B:0x0A — the 0x0A verifies two-digit padding.
  assert.match(go, /AmberLight\s+= color\.RGBA\{R: 0xD4, G: 0x91, B: 0x0A, A: 0xFF\}/);
  assert.match(go, /AmberDark\s+= color\.RGBA\{R: 0xE9, G: 0xA6, B: 0x20, A: 0xFF\}/);
  // White is an emitted image-renderer primitive, not a token.
  assert.match(go, /var White = color\.RGBA\{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF\}/);
});

test('emitGoTokens omits the alpha tokens (amber-muted, overlay) that are not solid hex', () => {
  const go = emitGoTokens(tokens);
  assert.ok(!/AmberMuted/.test(go), 'amber-muted resolves to rgba(), not a solid hex');
  assert.ok(!/Overlay/.test(go), 'overlay resolves to rgba(), not a solid hex');
});

test('emitGoTokens aligns each const/var block so every = shares one column (gofmt-clean)', () => {
  const go = emitGoTokens(tokens);
  const blocks = go.match(/(?:const|var) \(\n([\s\S]*?)\n\)/g) ?? [];
  assert.ok(blocks.length === 2, 'expected exactly a const block and a var block');
  for (const block of blocks) {
    const cols = block
      .split('\n')
      .filter((l) => l.includes(' = '))
      .map((l) => l.indexOf(' = '));
    assert.ok(cols.length > 0);
    assert.ok(cols.every((c) => c === cols[0]), 'assignment "=" not aligned within a block');
  }
});

// --------------------------------------------------------------------------
// Share-page emitter: api-go/internal/sharepage/templates/tokens.gohtml
// --------------------------------------------------------------------------

test('emitSharepageTokensGohtml wraps a tokenVars block with light :root and dark @media', () => {
  const html = emitSharepageTokensGohtml(tokens);
  assert.match(html, /\{\{define "tokenVars"\}\}/);
  assert.match(html, /\{\{end\}\}/);
  assert.match(html, /:root\{/);
  assert.match(html, /@media \(prefers-color-scheme:dark\)\{/);
  // Provenance is a Go-template comment so it renders zero bytes into the CSS.
  assert.match(html, /\{\{\/\* GENERATED FILE/);
});

test('emitSharepageTokensGohtml uses the true neutral bucket (withdrawn), unlike the SEO block', () => {
  const html = emitSharepageTokensGohtml(tokens);
  // statusBuckets.neutral = status-withdrawn: #7A7570 light, #8E8A85 dark.
  assert.match(html, /--status-neutral:#7A7570;/);
  assert.match(html, /--status-neutral:#8E8A85;/);
  // Not text-secondary (#6B6560 / #9B9590) — that is the SEO block's neutral.
  assert.ok(!/--status-neutral:#6B6560/.test(html));
});

test('emitSharepageTokensGohtml emits compact rgba() fills at 15% (share-page style)', () => {
  const html = emitSharepageTokensGohtml(tokens);
  assert.match(html, /--status-granted-bg:rgba\(26,125,55,0\.15\);/); // #1A7D37 @ 15%
  assert.match(html, /--amber-muted:rgba\(212,145,10,0\.15\);/); // amber light @ 15%
  assert.ok(!/rgba\(26, 125, 55/.test(html), 'share-page rgba() has no spaces after commas');
});

test('emitSharepageTokensGohtml keeps layout invariants (radius/spacing) on the light :root only', () => {
  const html = emitSharepageTokensGohtml(tokens);
  const dark = html.slice(html.indexOf('@media'));
  assert.ok(!/--radius-sm/.test(dark), 'radius lives only on the light :root');
  assert.ok(!/--space-xs/.test(dark), 'spacing lives only on the light :root');
});

// --------------------------------------------------------------------------
// Drift gate: every generated output, tampered, fails --check
// --------------------------------------------------------------------------

test('--check exits 0 on a clean tree and non-zero once ANY generated file is tampered', () => {
  // Clean tree first (the committed files must already be in sync).
  execFileSync('node', [GENERATE, '--check'], { stdio: 'pipe' });

  for (const { path } of buildOutputs(tokens)) {
    const original = readFileSync(path, 'utf8');
    // Append a language-appropriate comment so the file is syntactically valid
    // yet no longer matches what the generator would produce.
    const marker = path.endsWith('.go')
      ? '\n// tampered\n'
      : path.endsWith('.gohtml')
        ? '\n{{/* tampered */}}\n'
        : '\n/* tampered */\n';
    try {
      writeFileSync(path, original + marker);
      let exitCode = 0;
      try {
        execFileSync('node', [GENERATE, '--check'], { stdio: 'pipe' });
      } catch (err) {
        exitCode = err.status;
      }
      assert.notEqual(exitCode, 0, `--check should fail when ${path} is stale`);
    } finally {
      // Restore the committed content regardless of assertion outcome.
      run(); // regenerate from tokens.json
      assert.equal(readFileSync(path, 'utf8'), original, `generated file ${path} was not restored`);
    }
  }
});
