// Code generated by scripts/design-tokens/generate.mjs. DO NOT EDIT.

import SwiftUI

// MARK: - Brand

extension Color {
  /// Primary accent. Warm gold evoking town crier bells.
  public static let tcAmber = Color.themed(light: 0x9E6709, dark: 0xE9A620, oled: 0xE9A620)

  /// Lower-emphasis accent for secondary buttons and tags.
  public static let tcAmberMuted = tcAmber.opacity(0.12)
}

// MARK: - Surfaces

extension Color {
  /// Page-level background.
  public static let tcBackground = Color.themed(light: 0xF5F0E6, dark: 0x191713, oled: 0x000000)

  /// Card and component background.
  public static let tcSurface = Color.themed(light: 0xFFFDF6, dark: 0x23201A, oled: 0x0A0908)

  /// Modals, bottom sheets, popovers.
  public static let tcSurfaceElevated = Color.themed(
    light: 0xFFFDF6, dark: 0x2B2822, oled: 0x151310)
}

// MARK: - Text

extension Color {
  /// Body text and headings.
  public static let tcTextPrimary = Color.themed(light: 0x24201A, dark: 0xEFE9DC, oled: 0xEFE9DC)

  /// Captions, metadata, timestamps.
  public static let tcTextSecondary = Color.themed(light: 0x6D665C, dark: 0xA69E8F, oled: 0xA69E8F)

  /// Placeholder text, disabled labels.
  public static let tcTextTertiary = Color.themed(light: 0xA79E90, dark: 0x6E675B, oled: 0x6E675B)

  /// Text rendered on tcAmber backgrounds.
  public static let tcTextOnAccent = Color.themed(light: 0xFFFDF8, dark: 0x1C1917, oled: 0x1C1917)
}

// MARK: - Status

extension Color {
  /// Application granted (PlanIt `Permitted`).
  public static let tcStatusPermitted = Color.themed(
    light: 0x1A7D37, dark: 0x34C759, oled: 0x34C759)

  /// Application granted with conditions (PlanIt `Conditions`).
  /// Amber/orange — granted but constrained, distinct from outright approval.
  public static let tcStatusConditions = Color.themed(
    light: 0xB85C00, dark: 0xFF9F0A, oled: 0xFF9F0A)

  /// Application refused (PlanIt `Rejected`).
  public static let tcStatusRejected = Color.themed(
    light: 0xC42B2B, dark: 0xFF453A, oled: 0xFF453A)

  /// Awaiting decision / under review.
  public static let tcStatusPending = Color.themed(light: 0xC27A0A, dark: 0xFFB340, oled: 0xFFB340)

  /// Application withdrawn.
  public static let tcStatusWithdrawn = Color.themed(
    light: 0x7A7570, dark: 0x8E8A85, oled: 0x8E8A85)

  /// Decision under appeal.
  public static let tcStatusAppealed = Color.themed(light: 0x7C3AED, dark: 0xA78BFA, oled: 0xA78BFA)
}

// MARK: - Utility

extension Color {
  /// Subtle dividers and card outlines.
  public static let tcBorder = Color.themed(light: 0xDAD2C2, dark: 0x3A352B, oled: 0x26221A)

  /// Focus rings and active input borders.
  public static let tcBorderFocused = tcAmber

  /// Semi-transparent scrim behind modals.
  public static let tcOverlay = Color.black.opacity(0.4)
}
