config:
  azure-native:location: uksouth
  town-crier:environment: prod
  town-crier:cosmosConsistencyLevel: Session
  town-crier:frontendDomain: towncrierapp.uk
  town-crier:apiDomain: api.towncrierapp.uk
  town-crier:customDomainPhase: "1"
  town-crier:skipCosmosDb: "true"
