// Code generated by scripts/design-tokens/generate.mjs. DO NOT EDIT.

// Package designtokens is the Go projection of design/tokens.json (ADR 0040):
// the single source of truth for Town Crier's colour palette. Each solid colour
// token is exposed as a hex-string const (for HTML/CSS template consumers) and
// as a color.RGBA var (for image renderers such as the share-page OG card).
//
// Only light and dark themes are emitted: no Go-rendered surface implements the
// OLED theme. The alpha tokens (amber-muted, overlay) resolve to rgba() rather
// than a solid hex and are intentionally omitted; a Go consumer needing a
// translucent fill composes it explicitly.
package designtokens

import "image/color"

// Hex strings per theme (leading '#'), for HTML/CSS template consumers.
const (
	AmberLightHex            = "#D4910A"
	AmberDarkHex             = "#E9A620"
	AmberHoverLightHex       = "#B87A08"
	AmberHoverDarkHex        = "#F0B83A"
	BackgroundLightHex       = "#FAF8F5"
	BackgroundDarkHex        = "#1A1A1E"
	SurfaceLightHex          = "#FFFFFF"
	SurfaceDarkHex           = "#242428"
	SurfaceElevatedLightHex  = "#FFFFFF"
	SurfaceElevatedDarkHex   = "#2E2E33"
	TextPrimaryLightHex      = "#1C1917"
	TextPrimaryDarkHex       = "#F1EFE9"
	TextSecondaryLightHex    = "#6B6560"
	TextSecondaryDarkHex     = "#9B9590"
	TextTertiaryLightHex     = "#A39E98"
	TextTertiaryDarkHex      = "#5C5852"
	TextOnAccentLightHex     = "#FFFFFF"
	TextOnAccentDarkHex      = "#1C1917"
	StatusPermittedLightHex  = "#1A7D37"
	StatusPermittedDarkHex   = "#34C759"
	StatusConditionsLightHex = "#B85C00"
	StatusConditionsDarkHex  = "#FF9F0A"
	StatusRejectedLightHex   = "#C42B2B"
	StatusRejectedDarkHex    = "#FF453A"
	StatusPendingLightHex    = "#C27A0A"
	StatusPendingDarkHex     = "#FFB340"
	StatusWithdrawnLightHex  = "#7A7570"
	StatusWithdrawnDarkHex   = "#8E8A85"
	StatusAppealedLightHex   = "#7C3AED"
	StatusAppealedDarkHex    = "#A78BFA"
	BorderLightHex           = "#E8E4DF"
	BorderDarkHex            = "#3A3A3F"
	BorderFocusedLightHex    = "#D4910A"
	BorderFocusedDarkHex     = "#E9A620"
)

// RGBA values for image renderers. color.RGBA is alpha-premultiplied; every
// brand colour here is fully opaque (A: 0xFF), so R/G/B are the raw channels.
var (
	AmberLight            = color.RGBA{R: 0xD4, G: 0x91, B: 0x0A, A: 0xFF}
	AmberDark             = color.RGBA{R: 0xE9, G: 0xA6, B: 0x20, A: 0xFF}
	AmberHoverLight       = color.RGBA{R: 0xB8, G: 0x7A, B: 0x08, A: 0xFF}
	AmberHoverDark        = color.RGBA{R: 0xF0, G: 0xB8, B: 0x3A, A: 0xFF}
	BackgroundLight       = color.RGBA{R: 0xFA, G: 0xF8, B: 0xF5, A: 0xFF}
	BackgroundDark        = color.RGBA{R: 0x1A, G: 0x1A, B: 0x1E, A: 0xFF}
	SurfaceLight          = color.RGBA{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF}
	SurfaceDark           = color.RGBA{R: 0x24, G: 0x24, B: 0x28, A: 0xFF}
	SurfaceElevatedLight  = color.RGBA{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF}
	SurfaceElevatedDark   = color.RGBA{R: 0x2E, G: 0x2E, B: 0x33, A: 0xFF}
	TextPrimaryLight      = color.RGBA{R: 0x1C, G: 0x19, B: 0x17, A: 0xFF}
	TextPrimaryDark       = color.RGBA{R: 0xF1, G: 0xEF, B: 0xE9, A: 0xFF}
	TextSecondaryLight    = color.RGBA{R: 0x6B, G: 0x65, B: 0x60, A: 0xFF}
	TextSecondaryDark     = color.RGBA{R: 0x9B, G: 0x95, B: 0x90, A: 0xFF}
	TextTertiaryLight     = color.RGBA{R: 0xA3, G: 0x9E, B: 0x98, A: 0xFF}
	TextTertiaryDark      = color.RGBA{R: 0x5C, G: 0x58, B: 0x52, A: 0xFF}
	TextOnAccentLight     = color.RGBA{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF}
	TextOnAccentDark      = color.RGBA{R: 0x1C, G: 0x19, B: 0x17, A: 0xFF}
	StatusPermittedLight  = color.RGBA{R: 0x1A, G: 0x7D, B: 0x37, A: 0xFF}
	StatusPermittedDark   = color.RGBA{R: 0x34, G: 0xC7, B: 0x59, A: 0xFF}
	StatusConditionsLight = color.RGBA{R: 0xB8, G: 0x5C, B: 0x00, A: 0xFF}
	StatusConditionsDark  = color.RGBA{R: 0xFF, G: 0x9F, B: 0x0A, A: 0xFF}
	StatusRejectedLight   = color.RGBA{R: 0xC4, G: 0x2B, B: 0x2B, A: 0xFF}
	StatusRejectedDark    = color.RGBA{R: 0xFF, G: 0x45, B: 0x3A, A: 0xFF}
	StatusPendingLight    = color.RGBA{R: 0xC2, G: 0x7A, B: 0x0A, A: 0xFF}
	StatusPendingDark     = color.RGBA{R: 0xFF, G: 0xB3, B: 0x40, A: 0xFF}
	StatusWithdrawnLight  = color.RGBA{R: 0x7A, G: 0x75, B: 0x70, A: 0xFF}
	StatusWithdrawnDark   = color.RGBA{R: 0x8E, G: 0x8A, B: 0x85, A: 0xFF}
	StatusAppealedLight   = color.RGBA{R: 0x7C, G: 0x3A, B: 0xED, A: 0xFF}
	StatusAppealedDark    = color.RGBA{R: 0xA7, G: 0x8B, B: 0xFA, A: 0xFF}
	BorderLight           = color.RGBA{R: 0xE8, G: 0xE4, B: 0xDF, A: 0xFF}
	BorderDark            = color.RGBA{R: 0x3A, G: 0x3A, B: 0x3F, A: 0xFF}
	BorderFocusedLight    = color.RGBA{R: 0xD4, G: 0x91, B: 0x0A, A: 0xFF}
	BorderFocusedDark     = color.RGBA{R: 0xE9, G: 0xA6, B: 0x20, A: 0xFF}
)

// White is pure #FFFFFF — an image-renderer primitive (pin outline, on-accent
// text) that is white in every theme. It is not a design token.
var White = color.RGBA{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xFF}
