#!/usr/bin/env bash
# Verify the committed, generated design-token files are in sync with their
# single source of truth (design/tokens.json). Run by
# .github/workflows/design-token-drift-check.yml on every PR that touches the
# tokens, the generator, or a generated output.
#
# Canonical source:
#   - design/tokens.json — the hand-ordered single source of truth (ADR 0040).
#
# Generated outputs guarded (regenerated by scripts/design-tokens/generate.mjs):
#   - web/src/styles/tokens.css            (SPA custom-property sheet)
#   - web/scripts/lib/tokens.generated.mjs (SEO/share-page token block)
#
# If this fails, run `node scripts/design-tokens/generate.mjs` and commit the result.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

node "$REPO_ROOT/scripts/design-tokens/generate.mjs" --check
