#!/usr/bin/env bash
# Verify the committed, generated design-token files are in sync with their
# single source of truth (design/tokens.json). Run by
# .github/workflows/design-token-drift-check.yml on every PR that touches the
# tokens, the generator, or a generated output.
#
# Canonical source:
#   - design/tokens.json — the hand-ordered single source of truth (ADR 0040).
#
# Generated outputs guarded (regenerated by scripts/design-tokens/generate.mjs):
#   - web/src/styles/tokens.css                                (SPA custom-property sheet)
#   - web/scripts/lib/tokens.generated.mjs                     (SEO/share-page token block)
#   - api-go/internal/designtokens/tokens_gen.go               (Go palette projection)
#   - api-go/internal/sharepage/templates/tokens.gohtml        (share-page CSS token block)
#   - mobile/ios/.../DesignSystem/Colors/Color+TownCrier.swift (iOS colours)
#   - mobile/android/.../designsystem/Color.kt                 (Android colours)
#   - .claude/skills/design-language/references/tokens.md      (skill value tables)
#
# The generator's --check mode diffs every output registered in buildOutputs(),
# so this script covers all seven with no per-file logic here. Mobile generation
# is colours only; the skill doc regenerates only the value tables between its
# <!-- tokens:generated --> markers (ADR 0040).
#
# Also guarded — the Android launcher-icon foregrounds (issue #860, R7),
# regenerated by scripts/design-tokens/generate-android-icon.mjs from the iOS
# app-icon master (mobile/ios/.../AppIcon.appiconset/AppIcon.png):
#   - mobile/android/app/src/main/res/mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/ic_launcher_foreground.png
# Its --check decodes each committed PNG and pixel-compares against a fresh
# downscale (robust to DEFLATE bytes differing across Node/zlib versions).
#
# If this fails, run `node scripts/design-tokens/generate.mjs` (tokens) and/or
# `node scripts/design-tokens/generate-android-icon.mjs` (Android icon) and
# commit the result.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

node "$REPO_ROOT/scripts/design-tokens/generate.mjs" --check
node "$REPO_ROOT/scripts/design-tokens/generate-android-icon.mjs" --check
